const OK_CREATED = 201;
const ERROR_BED_REQUEST = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_INTERNAL_SERVER = 500;

module.exports = {
  OK_CREATED,
  ERROR_BED_REQUEST,
  ERROR_NOT_FOUND,
  ERROR_INTERNAL_SERVER,
};